[tool.poetry]
name = "egeria-workspaces"
version = "5.3"
description = ""
authors = ["Dan Wolfson <dwolfson@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.8"
jupyter = "*"
rich = "^13.9.4"
pyegeria = "*"
unitycatalog = "*"
textual = "*"
apache-airflow = "^2.10.4"
apache-airflow-providers-postgres = "^6.0.0"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
