# SPDX-License-Identifier: Apache-2.0

services:
  airflow:
    image: bitnami/airflow:2
    ports:
      - "8070:8070"
    env_file:
      - openlineage.env
    environment:
      - AIRFLOW_USERNAME=airflow
      - AIRFLOW_PASSWORD=airflow
      - AIRFLOW_EMAIL=airflow@example.com
      - AIRFLOW_FERNET_KEY=Z2uDm0ZL60fXNkEXG8LW99Ki2zf8wkmIltaTz1iQPDU=
      - AIRFLOW_DATABASE_HOST=postgres
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5436/airflow
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_CONN_EXAMPLE_DB=postgres://example:example@postgres:5432/example
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8070
      - OPENLINEAGE_CONFIG=/opt/bitnami/airflow/openlineage.yml

    volumes:
      - ../../runtime-volumes/airflow-volumes/dags:/opt/bitnami/airflow/dags
      - ${PWD}/whl:/whl
      - ../../exchange/distribution-hub:/mnt/distribution-hub
      - type: bind
        source: ${PWD}/requirements.txt
        target: /bitnami/python/requirements.txt
      - type: bind
        source: ${PWD}/openlineage.yml
        target: /opt/bitnami/airflow/openlineage.yml

  airflow_scheduler:
    image: bitnami/airflow-scheduler:2
    env_file:
      - openlineage.env
    environment:
      - AIRFLOW_FERNET_KEY=Z2uDm0ZL60fXNkEXG8LW99Ki2zf8wkmIltaTz1iQPDU=
      - AIRFLOW_DATABASE_HOST=postgres
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5436/airflow
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_CONN_EXAMPLE_DB=postgres://example:example@postgres:5432/example
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8070
      - OPENLINEAGE_CONFIG=/opt/bitnami/airflow/openlineage.yml

    volumes:
      - ../../runtime-volumes/airflow-volumes/dags:/opt/bitnami/airflow/dags
      - ../../exchange/distribution-hub:/mnt/distribution-hub
      - ${PWD}/whl:/whl
      - type: bind
        source: ${PWD}/requirements.txt
        target: /bitnami/python/requirements.txt
      - type: bind
        source: ${PWD}/openlineage.yml
        target: /opt/bitnami/airflow/openlineage.yml

  airflow_worker:
    image: bitnami/airflow-worker:2
    env_file:
      - openlineage.env
    environment:
      - AIRFLOW_FERNET_KEY=Z2uDm0ZL60fXNkEXG8LW99Ki2zf8wkmIltaTz1iQPDU=
      - AIRFLOW_DATABASE_HOST=postgres
#      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5436/airflow
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_CONN_EXAMPLE_DB=postgres://example:example@postgres:5432/example
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8070
      - AIRFLOW__OPENLINEAGE__CONFIG_PATH='/opt/bitnami/airflow/openlineage.yml'


    volumes:
      - ../../runtime-volumes/airflow-volumes/dags:/opt/bitnami/airflow/dags
      - ../../exchange/distribution-hub:/mnt/distribution-hub
      - ${PWD}/whl:/whl
      - type: bind
        source: ${PWD}/requirements.txt
        target: /bitnami/python/requirements.txt
      - type: bind
        source: ${PWD}/openlineage.yml
        target: /opt/bitnami/airflow/openlineage.yml

  marquez:
    image: marquezproject/marquez:latest
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5050
      - MARQUEZ_ADMIN_PORT=5051

    ports:
      - "5050:5050"
      - "5051:5051"
    volumes:
      - ./docker/wait-for-it.sh:/usr/src/app/wait-for-it.sh
    depends_on:
      - postgres
    entrypoint: ["./wait-for-it.sh", "postgres:5436", "--", "./entrypoint.sh"]
    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
    # command: ["postgres", "-c", "log_statement=all"]

  marquez_web:
    image: marquezproject/marquez-web:latest
    environment:
      - MARQUEZ_HOST=marquez
      - MARQUEZ_PORT=5050
      - REACT_APP_ADVANCED_SEARCH=false
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - marquez

  postgres:
    image: bitnami/postgresql:12.1.0
    ports:
      - "543:5432"
#    command: postgres -p 5436 --config-file=/var/lib/postgresql/data/pgdata/postgresql.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - AIRFLOW_USER=airflow
      - AIRFLOW_PASSWORD=airflow
      - AIRFLOW_DB=airflow
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
      - MARQUEZ_DB=marquez
      - EXAMPLE_USER=example
      - EXAMPLE_PASSWORD=example
      - EXAMPLE_DB=example
      - ALLOW_EMPTY_PASSWORD=yes
#      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

#      - ../../runtime-volumes/airflow-pg:/var/lib/postgresql/data/pgdata

  redis:
    image: bitnami/redis:6.0.6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  airflow-python:
    profiles:
      - debug
    environment:
      - AIRFLOW_FERNET_KEY=Z2uDm0ZL60fXNkEXG8LW99Ki2zf8wkmIltaTz1iQPDU=
      - AIRFLOW_DATABASE_HOST=postgres
      #      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5436/airflow
      - AIRFLOW_DATABASE_NAME=airflow
      - AIRFLOW_DATABASE_USERNAME=airflow
      - AIRFLOW_DATABASE_PASSWORD=airflow
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
      - AIRFLOW_CONN_EXAMPLE_DB=postgres://example:example@postgres:5432/example
      - AIRFLOW_WEBSERVER_HOST=airflow
      - AIRFLOW_WEBSERVER_PORT_NUMBER=8070
      - OPENLINEAGE_CONFIG=/opt/bitnami/airflow/openlineage.yml
    user: "50000:0"
    entrypoint: [ "bash" ]

#networks:
#  egeria_network:
##    driver: bridge
#    external: true